apiVersion: v1
kind: ConfigMap
metadata:
  name: historyserver-config
data:
  flink-conf.yaml: |
    {{- .Values.flinkConfigMap | nindent 4 }}
  log4j-console.properties: |
    {{- .Values.log4jConfigMap | nindent 4 }}
