apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: {{ .Release.Name }}-efs-flink-history-sc
parameters:
  provisioningMode: efs-ap
  fileSystemId: "{{- .Values.efsFileSystemId }}"
provisioner: "efs.csi.aws.com"
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Release.Name }}-flink-historyserver-efs-pv
spec:
  capacity:
    storage: "1Mi"
  volumeMode: "Filesystem"
  accessModes:
    - "ReadWriteMany"
  # 'persistentVolumeReclaimPolicy' means EFS volumes must be manually cleaned up when testing is done
  persistentVolumeReclaimPolicy: Retain
  storageClassName: {{ .Release.Name }}-efs-flink-history
  csi:
    driver: "efs.csi.aws.com"
    volumeHandle: "{{- .Values.efsFileSystemId }}"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: flink-historyserver-efs-pvc
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: {{ .Release.Name }}-efs-flink-history-sc
  resources:
    requests:
      storage: 1Mi
