{
 "title": "Flink Jobs Dashboard",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "tmregex", "label": "TaskManager Regex", "query": ".*taskmanager.*" }
  ]
 },
 "panels": [
  {
   "title": "Task Manager Flink Memory",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "flink_taskmanager_Status_Flink_Memory_Managed_Used{pod=~\"$tmregex\"}",
     "legendFormat": "{{pod}}-Used"
    },
    {
     "expr": "flink_taskmanager_Status_Flink_Memory_Managed_Total{pod=~\"$tmregex\"}",
     "legendFormat": "{{pod}}-Total"
    }
   ]
  },
  {
   "title": "Task Manager JVM Heap Max",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "flink_taskmanager_Status_JVM_Memory_Heap_Max{pod=~\"$tmregex\"}",
     "legendFormat": "{{pod}}-Max-Heap"
    }
   ]
  },
  {
   "title": "Task Manager JVM NonHeap",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "flink_taskmanager_Status_JVM_Memory_NonHeap_Max{pod=~\"$tmregex\"}",
     "legendFormat": "{{pod}}-Max-NonHeap"
    },
    {
     "expr": "flink_taskmanager_Status_JVM_Memory_NonHeap_Used{pod=~\"$tmregex\"}",
     "legendFormat": "{{pod}}-Used-NonHeap"
    }
   ]
  },
  {
   "title": "Task Manager JVM Other",
   "type": "timeseries",
   "description": "Metaspace, Mapped Memory",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "flink_taskmanager_Status_JVM_Memory_Metaspace_Used{pod=~\"$tmregex\"}",
     "legendFormat": "{{pod}}-Metaspace-Used"
    },
    {
     "expr": "flink_taskmanager_Status_JVM_Memory_Metaspace_Max{pod=~\"$tmregex\"}",
     "legendFormat": "{{pod}}-Metaspace-Max"
    },
    {
     "expr": "flink_taskmanager_Status_JVM_Memory_Mapped_TotalCapacity{pod=~\"$tmregex\"}",
     "legendFormat": "{{pod}}-Mapped-Total"
    },
    {
     "expr": "flink_taskmanager_Status_JVM_Memory_Mapped_MemoryUsed{pod=~\"$tmregex\"}",
     "legendFormat": "{{pod}}-Mapped-Used"
    }
   ]
  },
  {
   "title": "Task Manager JVM Heap Usage",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "flink_taskmanager_Status_JVM_Memory_Heap_Used{pod=~\"$tmregex\"}",
     "legendFormat": "{{pod}}-Used-Heap"
    }
   ]
  },
  {
   "title": "Task Manager JVM Direct",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "flink_taskmanager_Status_JVM_Memory_Direct_MemoryUsed{pod=~\"$tmregex\"}",
     "legendFormat": "{{pod}}-Direct-Used"
    },
    {
     "expr": "flink_taskmanager_Status_JVM_Memory_Direct_TotalCapacity{pod=~\"$tmregex\"}",
     "legendFormat": "{{pod}}-Direct-Total"
    }
   ]
  },
  {
   "title": "Job Task Num Records In",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 12 },
   "targets": [
    {
     "expr": "flink_taskmanager_job_task_numRecordsIn{pod=~\"$tmregex\"}",
     "legendFormat": "{{pod}}-num-jobs-in"
    }
   ]
  },
  {
   "title": "Job Task Num Records Out Per Second",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 12 },
   "targets": [
    {
     "expr": "flink_taskmanager_job_task_numRecordsOutPerSecond{pod=~\"$tmregex\"}",
     "legendFormat": "{{pod}}-recs-out-per-sec"
    }
   ]
  },
  {
   "title": "Flink Operator JVM Heap",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "flink_k8soperator_Status_JVM_Memory_Heap_Used{name=\"flink_kubernetes_operator\"}",
     "legendFormat": "{{pod}}-Used"
    },
    {
     "expr": "flink_k8soperator_Status_JVM_Memory_Heap_Max{name=\"flink_kubernetes_operator\"}",
     "legendFormat": "{{pod}}-Max"
    }
   ]
  }
 ]
}